### ISSUE TITLE
Dockerfile contents

### ISSUE THREAD

**Issue by kkebb** [xemuliam/docker-nifi-base#5]
Can you share your Dockerfile in the repo?

**Comment by kkebb** [comment]
Never mind I found it in the docker hub registry :)

**Comment by kkebb** [comment]
Although it would be nice to have it posted in the git repo as well for contributions and version control.

**Comment by xemuliam** [comment]
Docker files are in corresponding branches
Here it is an example:
https://github.com/xemuliam/docker-nifi-base/blob/1.1.2/Dockerfile

However please bear in mind that this is just base image.
Real images for implementation are in separate repository:
https://github.com/xemuliam/docker-nifi
